### ISSUE TITLE
Ease of font re-ordering for performance

### ISSUE THREAD

**Issue by svgeesus** [w3c/IFT#117] opened 2022-08-25 13:20 UTC
[Originally raised by Martin Thomson](https://lists.w3.org/Archives/Public/ietf-http-wg/2022AprJun/0279.html)

> I do like the idea of specifying how a font might be laid out to make it easier to process in pieces, but some of this seems very optimistic about what people will be able to do with fonts to make them faster for pages.

**Comment by svgeesus** [comment] 2022-08-25 13:21
We should point to emerging tools which can perform this. 

Also compare and contrast ease of changing content vs. changing server config, which many users have no control over.

**Comment by tiroj** [comment] 2022-08-27 00:56
Of possible relevance: Microsoft had an old command line tool called fastfont that would sort TTF tables in optimised order for processing. The order it used might be a starting place, although web use might benefit from different optimisations.

**Comment by garretrieger** [comment] 2022-09-09 23:34
Myle's has already built some tooling to do the reordering: https://github.com/litherum/StreamableFonts

I expect it will need more work, but in general I think the plan would be to have some open source tooling available along side the spec that people hosting fonts can run their fonts through.

**Comment by garretrieger** [comment] 2022-09-13 22:05
Duplicate of #110

**Closed by garretrieger** 2022-09-13 22:05 UTC
Labels: Range Request

**Comment by svgeesus** [comment] 2022-09-14 16:02
@martinthomson we responded to your points, but then latter closed this as a duplicate to focus discussion. You are tagged on the other issue.
