### ISSUE TITLE
Why do we have two methods

### ISSUE THREAD

**Issue by svgeesus** [w3c/IFT#120] opened 2022-08-25 13:44 UTC
Originally reported by Martin Thomson, and [expanded upon here]():

>> On Mon, Jul 4, 2022, at 22:35, Chris Lilley wrote:
>> https://www.w3.org/TR/PFE-evaluation/

> Thanks for the context.

> I found this interesting, but wasn't able to reach the same conclusions here based on what was presented here.  Even taking it as given that a font subset is smaller, the network simulation here looks fancy, but my experience with simulation is that it is not worth much.  A real-world evaluation will include packet loss and contention with other activity.  That includes some impact from processing time, which I am guessing will be a factor here.

> What the performance evaluation doesn't say is how much the (purported) performance regressions correlated with poor (simulated) network conditions.  I might infer from this that the users on the worst networks suffered the worst, but that isn't necessarily how something like this ends up working in practice.  

> To take a different example, with QUIC, Google's initial experiments[0] showed that the regressions were observed for people on really fast networks.  The best theory there was that QUIC was a little more complex, so it involved spending a bit more CPU, which on a fast network became the determining factor.

> QUIC was overwhelmingly good for people on bad networks.  Improvements got larger as networks got worse.  Here, it looks like you might have something that makes the people with the slowest 5% of connections slower. That would be a poor outcome if it is the case.

**Comment by svgeesus** [comment] 2022-08-25 13:51
>  it looks like you might have something that makes the people with the slowest 5% of connections slower. That would be a poor outcome if it is the case.

Correct, our analysis (see Figure 23) showed that [for CJK fonts, using the `range-request` method](https://www.w3.org/TR/PFE-evaluation/#analysis-cjk) made the experience considerably worse on 3G networks than just downloading the whole font. On 2G networks, both methods were significantly  worse than downloading the whole font.

That is why [we concluded](https://www.w3.org/TR/PFE-evaluation/#conclusions-cjk):

>  For the first time, **on 4G and faster networks**, Patch Subset makes CJK Webfonts a realistic resource, rather than being completely unusable.

> **On 3G networks, Patch Subset may still be usable** for CJK Webfonts (improving page load times in many but not all cases, while worsening them in others). 

> **On 2G networks**, the byte savings from Range Request are outweighed by the **massive cost increases of all methods**. Relying on pre-installed fonts for CJK content on 2G networks remains the only viable solution, alas.

**Comment by svgeesus** [comment] 2022-08-25 14:06
> Even taking it as given that a font subset is smaller, 

We don't have to take that as given, we have data. See [bytes transferred](https://www.w3.org/TR/PFE-evaluation/#analysis-cjk) in particular Figure 21, which shows a median 90% reduction in bytes transferred, for the `patch subset` method.

> the network simulation here looks fancy, but my experience with simulation is that it is not worth much. A real-world evaluation will include packet loss and contention with other activity. 

Naturally, once we have defined the network and data representation aspects, we will be running real-world performance trials with real fonts and real text content in the various language groups.

**Comment by svgeesus** [comment] 2022-08-25 14:08
In general, the _"why do we have two methods"_ question is now addressed [in the introduction to the IFT specification](https://w3c.github.io/IFT/Overview.html#intro)

**Comment by svgeesus** [comment] 2022-08-25 14:11
Choosing between the two methods (or not using incremental transfer at all) is described in [1.4.2. Deciding between Patch Subset and Range Request](https://w3c.github.io/IFT/Overview.html#patchsubset-vs-rangerequest)

**Comment by garretrieger** [comment] 2022-09-13 22:10
Duplicate of #104

**Closed by garretrieger** 2022-09-13 22:10 UTC
Labels: Range Request, Patch Subset

**Comment by svgeesus** [comment] 2022-09-14 15:59
@martinthomson we closed this as a duplicate, but you are tagged on the other issue as well.
